export type Landmark = {
  id: string;
  name: string;
  neighborhood: string;
  address: string;
  subway: string;
  hours: string;
  ticket: string;
  timeNeeded: string;
  whatToDo: string;
  soloTip: string;
  bestTime: string;
};

export const LANDMARKS: Landmark[] = [
  {
    id: "statue-of-liberty",
    name: "Statue of Liberty & Ellis Island",
    neighborhood: "New York Harbor (depart from Battery Park)",
    address: "Liberty Island, New York, NY 10004",
    subway: "1 to South Ferry; 4/5 to Bowling Green; R/W to Whitehall St",
    hours: "Ferries 9:00 AM - 3:30 PM most days (last entry varies by season)",
    ticket: "~$25-30 ferry + grounds access. Pedestal/crown access requires separate timed booking, often 2-3 months ahead.",
    timeNeeded: "Half day (4-5 hours including ferry both ways and Ellis Island)",
    whatToDo: "Take the Statue Cruises ferry, walk Liberty Island grounds, take the included Ellis Island Immigration Museum tour. Skip the crown if you have any mobility limitations - it's 354 narrow stairs.",
    soloTip: "Solo tickets are easier to get than family bundles for crown access. Book the earliest ferry slot you can - lines are dramatically shorter at 9 AM than 11 AM.",
    bestTime: "First ferry of the morning, weekdays only if possible.",
  },
  {
    id: "empire-state-building",
    name: "Empire State Building",
    neighborhood: "Midtown Manhattan",
    address: "20 W 34th St, New York, NY 10001",
    subway: "B/D/F/M/N/Q/R/W to 34 St-Herald Sq; 6 to 33 St",
    hours: "Daily, typically 10:00 AM - 12:00 AM (last entry around 11:15 PM)",
    ticket: "~$44 for the 86th floor observatory; ~$79 for combo with 102nd floor; express passes more.",
    timeNeeded: "1.5 - 2 hours including security and elevators",
    whatToDo: "86th floor outdoor observatory has the iconic view. 102nd floor is enclosed and higher but a much smaller deck. Don't skip the Art Deco lobby - it's a landmark in its own right.",
    soloTip: "Sunset is the most popular slot (and the most crowded). Solo travelers do well with 9 PM-10 PM tickets - skyline lights are full-on, lines are gone, and you'll have room to move around the deck.",
    bestTime: "After 9 PM for fewest crowds; sunrise (very early entry) for solitude.",
  },
  {
    id: "top-of-the-rock",
    name: "Top of the Rock (Rockefeller Center)",
    neighborhood: "Midtown Manhattan",
    address: "30 Rockefeller Plaza, New York, NY 10112",
    subway: "B/D/F/M to 47-50 Sts - Rockefeller Center",
    hours: "Daily 9:00 AM - 11:00 PM (varies seasonally)",
    ticket: "~$40 standard; $50+ for sunset slots; ~$75 for sunrise.",
    timeNeeded: "1 - 1.5 hours",
    whatToDo: "Three-tier observation deck. The big advantage over Empire State is that Empire State is in the view (you can't see it from Empire State because you're standing on it). Best skyline shot in NYC.",
    soloTip: "Picking Top of the Rock over Empire State is the move most New Yorkers recommend to first-timers for exactly the reason above. Sunset is worth the premium if your budget allows.",
    bestTime: "30 minutes before sunset; arrive early to claim a railing spot on the south-facing side.",
  },
  {
    id: "911-memorial-museum",
    name: "9/11 Memorial & Museum",
    neighborhood: "Financial District",
    address: "180 Greenwich St, New York, NY 10007",
    subway: "1 to WTC Cortlandt; E to World Trade Center; R/W to Cortlandt St; 2/3 to Park Place",
    hours: "Memorial plaza open daily 7:30 AM - 9:00 PM (free). Museum daily 9:00 AM - 7:00 PM (last entry 5:00 PM).",
    ticket: "Memorial plaza is free. Museum admission ~$33 (~$0 on Monday evenings 5-7 PM with timed entry, very limited supply).",
    timeNeeded: "Memorial: 30-45 min. Museum: 2-3 hours.",
    whatToDo: "Walk both reflecting pools first; read the names etched along the bronze parapets. The museum is emotionally heavy but essential - allow time and consider not pairing it with another somber experience the same day.",
    soloTip: "Going solo is actually appropriate here - it's a contemplative place, and most people speak quietly. Bring tissues. Plan something light afterward (a walk along the Hudson, a coffee, the Brookfield Place atrium next door).",
    bestTime: "Weekday morning. The museum is significantly less crowded than the memorial plaza outside.",
  },
  {
    id: "central-park",
    name: "Central Park",
    neighborhood: "Manhattan (spans 59th to 110th, 5th to 8th Avenue)",
    address: "Central Park, New York, NY",
    subway: "Many entrances - A/B/C/D/1 to Columbus Circle (south); 5 Av/59 St for southeast; 81/86/96/103 St on 8th Ave subway lines for west side",
    hours: "Daily 6:00 AM - 1:00 AM. Many areas effectively unwalkable after dark - stick to lit main paths.",
    ticket: "Free. The Zoo, Conservatory Garden tours, and some attractions charge separately.",
    timeNeeded: "Self-paced; allow at least 2 hours for a meaningful visit, a full day for a deep one.",
    whatToDo: "Bethesda Terrace + Fountain (the classic photo), the Bow Bridge, the Mall (the tree-lined promenade), Belvedere Castle, the Reservoir loop (1.58 mi running track), the Conservatory Garden (Upper East Side, often empty). Skip the horse carriages - they're overpriced and the welfare situation is questionable.",
    soloTip: "Central Park is one of the easiest places in NYC to be alone in a crowd. Rent a bike at the south entrance for $20-30 to cover ground fast, or do a self-guided walk from the Mall to Bethesda to Bow Bridge to the Lake (about 90 min, the park's greatest-hits).",
    bestTime: "Early morning for the Reservoir, weekday afternoons for the busy meadows, sunset on Sheep Meadow for skyline views.",
  },
  {
    id: "times-square",
    name: "Times Square",
    neighborhood: "Midtown Manhattan",
    address: "Broadway & 7th Ave, around 42nd-47th Streets",
    subway: "1/2/3/7/N/Q/R/W/S to Times Sq - 42 St",
    hours: "Always open; lights are on 24/7.",
    ticket: "Free to walk through. Most attractions inside (Madame Tussauds, Ripley's, etc.) are paid.",
    timeNeeded: "30 minutes is plenty to see it; longer if you're doing TKTS for Broadway tickets or attending a show.",
    whatToDo: "Walk the pedestrian plazas, see the lights at night, watch the street performers from a respectful distance (don't tip the costumed characters unless you want a photo). TKTS booth at the red steps sells same-day Broadway tickets at 20-50% discount from ~3 PM.",
    soloTip: "Most New Yorkers actively avoid Times Square. It's worth seeing once at night for the sensory experience, then leaving. Don't eat here (overpriced tourist traps line every block); walk two avenues away in any direction for better food.",
    bestTime: "After dark for the light effect; weekday evening to avoid weekend tourist crowds.",
  },
  {
    id: "brooklyn-bridge",
    name: "Brooklyn Bridge",
    neighborhood: "Lower Manhattan to DUMBO, Brooklyn",
    address: "Brooklyn Bridge, New York, NY",
    subway: "Manhattan side: 4/5/6 to Brooklyn Bridge - City Hall, J/Z to Chambers St. Brooklyn side: A/C to High St, F to York St.",
    hours: "24/7 pedestrian access.",
    ticket: "Free.",
    timeNeeded: "30-45 min to walk one way (1.1 miles). Add time at either end for photos.",
    whatToDo: "Walk Manhattan to Brooklyn (better view ahead of you). Stay in the pedestrian lane (white painted line) - the bike lane gets aggressive. Stop at the tower arches for the postcard photo. End in DUMBO for the Washington/Water Street arch shot of the bridge framing the Empire State Building.",
    soloTip: "Walk over at sunset - bridge is busy enough to feel safe and the light is stunning. Take an Uber or subway back rather than walking both ways. Avoid mid-day in summer (no shade, very crowded).",
    bestTime: "Sunset (1 hour before sundown), or sunrise for empty bridge and best photos.",
  },
  {
    id: "high-line",
    name: "The High Line",
    neighborhood: "Chelsea / West Side (Gansevoort St up to 34th St)",
    address: "Various entrances; Gansevoort St & Washington St is the south end.",
    subway: "A/C/E to 14 St (then walk west) for south end; 7 to 34 St-Hudson Yards for north end.",
    hours: "Daily 7:00 AM - 10:00 PM (varies seasonally, shorter in winter).",
    ticket: "Free. Timed entry sometimes required in peak summer.",
    timeNeeded: "1 - 1.5 hours to walk the full 1.45 miles.",
    whatToDo: "Walk south-to-north (downhill, ends at Hudson Yards and the Vessel). The garden plantings change month to month - it's an actual landscaped park, not just a walkway. Photo spots: the overlook at 17th St, the sundeck at 14th St, the views into apartment windows are unintentionally funny.",
    soloTip: "Walking the full length top-to-bottom is the move. Hop off at Chelsea Market (16th St exit) for lunch at a counter - perfect solo dining setup, and you can re-enter the High Line afterward.",
    bestTime: "Weekday morning. Weekend afternoons get genuinely crowded.",
  },
  {
    id: "met-museum",
    name: "The Metropolitan Museum of Art",
    neighborhood: "Upper East Side (Museum Mile)",
    address: "1000 5th Ave, New York, NY 10028",
    subway: "4/5/6 to 86 St then walk three blocks west; M1/M2/M3/M4 bus along 5th Ave",
    hours: "Sunday-Tuesday & Thursday 10:00 AM - 5:00 PM; Friday-Saturday 10:00 AM - 9:00 PM; closed Wednesday.",
    ticket: "$30 for non-NY-State residents (covers Met Fifth Ave + The Cloisters within 3 days). NY State residents and NY/NJ/CT students pay-what-you-wish.",
    timeNeeded: "Half day minimum; a full day for serious museum-goers.",
    whatToDo: "Egyptian wing (Temple of Dendur), European Paintings (Vermeer, Rembrandt), American Wing, Arms & Armor, the Roof Garden in season (open May-Oct, rotating sculpture installation, killer Central Park views). Get the museum map at the entrance.",
    soloTip: "Museums are the ultimate solo-friendly NYC activity - no awkwardness, no pace negotiation, can leave whenever. Friday/Saturday evenings (open till 9 PM) are dramatically quieter than weekend days. The roof bar at sunset, when open, is one of the best solo experiences in the city.",
    bestTime: "Friday or Saturday evening 5 PM onwards.",
  },
];
